Repository runtimeverification/evm-semantics, pull requests merged in 2022-10, with the labels that each got.

#1364 Rule for setNonce cheatcode
  foundry.md
  tests/foundry/exclude
  tests/foundry/foundry.k.check.expected
  tests/foundry/test/NonceTest.t.sol
Labels: automerge

#1409 Add new Foundry tests
  tests/foundry/exclude
  tests/foundry/foundry.k.check.expected
  tests/foundry/test/DealTest.t.sol
  tests/foundry/test/Etch.t.sol
Labels: automerge

#1406 foundry.md: refactor the CALL rules
  abi.md
  edsl.md
  foundry.md
  tests/foundry/exclude
  tests/specs/lemmas.k
Labels: automerge

#1413 Use #loadAccounts to for deal, etch, and getNonce cheat codes
  foundry.md
  tests/foundry/foundry.k.check.expected
  tests/foundry/test/DealTest.t.sol
  tests/foundry/test/Etch.t.sol
Labels: automerge

#1417 Update License
  LICENSE
Labels: automerge

#1415 Update `pyk` to v0.1.16
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge, kevm-pyk

#1419 Add rangeSmall to range of types
  tests/specs/mcd/functional-spec.k
  tests/specs/mcd/verification.k
  word.md
Labels: enhancement, automerge

#1395 Github workflows for PRs
  .github/actions/with-docker/action.yml
  .github/workflows/Dockerfile
  .github/workflows/Dockerfile.z3
  .github/workflows/test-pr.yml
  .github/workflows/test.yml
  .github/workflows/update-version.yml
  Jenkinsfile
  Makefile
  deps/k_release
  kevm
Labels: automerge

#1428 Container collision fix
  .github/workflows/test-pr.yml
Labels: automerge

#1430 Add rules for ABI encoding of bytes4 type
  abi.md
Labels: automerge

#1427 Generate individual KCFGs for each method in contract
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  kevm-pyk/src/kevm_pyk/solc_to_k.py
  kevm-pyk/src/kevm_pyk/utils.py
  tests/foundry/exclude
  tests/foundry/foundry.k.check.expected
  tests/foundry/test/DealTest.t.sol
Labels: automerge

#1434 Ignore binRuntime rules in foundry.k.check
  .gitignore
  Makefile
  tests/foundry/foundry.k.check.expected
Labels: automerge

#1431 Handle auto-updates from pyk repo
  .github/workflows/update-version.yml
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#1418 Remove docker hub stage & file
  Jenkinsfile
  package/docker/Dockerfile.ubuntu
Labels: bug, automerge

#1437 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#1438 Pass --md-selector to kprove too
  kevm
Labels: automerge

#1412 Implement startPrank and stopPrank rules
  foundry.md
  kevm-pyk/src/kevm_pyk/solc_to_k.py
  tests/foundry/exclude
  tests/foundry/foundry.k.check.expected
  tests/foundry/test/PlainPrankTest.t.sol
Labels: automerge

#1426 Revert for unimplemented cheat codes.
  foundry.md
  tests/foundry/exclude
  tests/foundry/foundry.k.check.expected
  tests/foundry/test/Simple.t.sol
Labels: automerge

#1429 Usability fixes for Foundry integration
  foundry.md
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  tests/foundry/foundry.k.check.expected
  tests/specs/functional/lemmas-spec.k
  tests/specs/lemmas.k
  word.md
Labels: automerge

#1433 Organize repository, move sources into subdirectories
  .github/workflows/test-pr.yml
  Makefile
  bin/kevm
  cmake/node/CMakeLists.txt
  flake.nix
  include/kframework/abi.md
  include/kframework/asm.md
  include/kframework/buf.md
  include/kframework/data.md
  include/kframework/driver.md
  include/kframework/edsl.md
  include/kframework/evm-imp-specs.md
  include/kframework/evm-node.md
  include/kframework/evm-types.md
  include/kframework/evm.md
  include/kframework/foundry.md
  include/kframework/hashed-locations.md
  include/kframework/infinite-gas.md
  include/kframework/issues.md
  include/kframework/json-rpc.md
  include/kframework/lemmas/int-simplification.k
  include/kframework/lemmas/lemmas.k
  include/kframework/network.md
  include/kframework/optimizations.md
  include/kframework/serialization.md
  include/kframework/state-utils.md
  include/kframework/word.md
  package/nix/kevm.patch
  tests/specs/benchmarks/verification.k
  tests/specs/bihu/verification.k
  tests/specs/erc20/verification.k
  tests/specs/examples/sum-to-n-spec.k
  tests/specs/functional/lemmas-no-smt-spec.k
  tests/specs/functional/lemmas-spec.k
  tests/specs/mcd/verification.k
  tests/specs/opcodes/verification.k
Labels: automerge
