Repository runtimeverification/evm-semantics, pull requests merged in 2023-11, with the labels that each got.

#2138 Remove option to skip simplifing init nodes
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/cli.py
  kevm-pyk/src/tests/integration/test_prove.py
  package/version
Labels: automerge

#2152 Factor out cut-point and terminal rules
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  kevm-pyk/src/kevm_pyk/utils.py
  kevm-pyk/src/kontrolx/foundry.py
  package/version
Labels: automerge

#2123 Move all runs to internal runners
  .github/workflows/test-pr.yml
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2155 Increase proof CI timeouts
  .github/workflows/test-pr.yml
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2118 Add infrastructure to KEVM for Maude Backend
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/cli.py
  kevm-pyk/src/kevm_pyk/kompile.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: enhancement, automerge

#2149 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2158 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2153 Move Additional Workflows to Ephemeral Runners
  .github/workflows/test-pr.yml
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2159 Correctly strip `-spec.k` from the bug report name in `prove_legacy`
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  package/version
Labels: automerge

#2163 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2154 Add target namespaces to `kdist`
  .github/workflows/test-pr.yml
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/interpreter.py
  kevm-pyk/src/kevm_pyk/kdist/__init__.py
  kevm-pyk/src/kevm_pyk/kdist/__main__.py
  kevm-pyk/src/kevm_pyk/kdist/_kdist.py
  kevm-pyk/src/kevm_pyk/kdist/plugin.py
  kevm-pyk/src/tests/integration/test_conformance.py
  kevm-pyk/src/tests/integration/test_kast.py
  kevm-pyk/src/tests/integration/test_prove.py
  kevm-pyk/src/tests/integration/test_run.py
  package/version
Labels: automerge

#2086 Add '--smt-tactic <s-expression>' command-line option
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: bug, automerge

#2166 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2136 Support function with `struct` and `array` argument types
  .github/workflows/test-pr.yml
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/abi.md
  package/version
  tests/specs/benchmarks/dynamicarray00-spec.k
  tests/specs/benchmarks/dynamicarray00.sol
  tests/specs/benchmarks/structarg00-spec.k
  tests/specs/benchmarks/structarg00.sol
  tests/specs/smoke
Labels: automerge

#2160 Fix temp directory being deleted too early
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  package/version
Labels: bug, automerge

#2169 Fix build instructions in `README.md`
  README.md
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2168 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2165 Remove long-running tests on pyk prover also run with booster
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
  tests/failing-symbolic.pyk
Labels: automerge

#2161 Update options: improve help for `view/show-kcfg`, refactor `rpc_args`
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/cli.py
  package/version
Labels: automerge

#2171 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2172 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2174 Correctly ordered arguments in `typed_args`
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  package/version
Labels: automerge

#2164 Inject `ccopts` directly into `kevm_kompile` and fix some tests
  Makefile
  README.md
  VERIFICATION.md
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/kdist/plugin.py
  kevm-pyk/src/kevm_pyk/kompile.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/optimizations.md
  kevm-pyk/src/tests/integration/test_prove.py
  package/test-package.sh
  package/version
  tests/specs/examples/sum-to-n-foundry-spec.k
  tests/specs/functional/infinite-gas-spec.k
Labels: automerge

#2179 Fix circular import
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kdist/plugin.py
  kevm-pyk/src/kevm_pyk/kompile.py
  package/version
Labels: automerge

#2178 Move `--port` arguments to `rpc_args`
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/cli.py
  package/version
Labels: automerge

#2175 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2181 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2183 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2182 Add change detection to `kdist`
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kdist/__init__.py
  kevm-pyk/src/kevm_pyk/kdist/_kdist.py
  kevm-pyk/src/kevm_pyk/kdist/api.py
  kevm-pyk/src/kevm_pyk/kdist/plugin.py
  kevm-pyk/src/kevm_pyk/kdist/utils.py
  package/version
Labels: automerge

#2185 Use new formula location for `cryptopp@8.6.0`
  README.md
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2186 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2187 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2184 Add parameter handling to `kdist`
  README.md
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kdist/__main__.py
  kevm-pyk/src/kevm_pyk/kdist/_kdist.py
  kevm-pyk/src/kevm_pyk/kdist/api.py
  kevm-pyk/src/kevm_pyk/kdist/plugin.py
  package/version
Labels: automerge

#2190 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2191 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2188 Add info about testing locally
  README.md
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2192 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2193 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2196 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2195 Extract class `KDist`
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/config.py
  kevm-pyk/src/kevm_pyk/interpreter.py
  kevm-pyk/src/kevm_pyk/kdist/__init__.py
  kevm-pyk/src/kevm_pyk/kdist/__main__.py
  kevm-pyk/src/kevm_pyk/kdist/_cache.py
  kevm-pyk/src/kevm_pyk/kdist/_kdist.py
  kevm-pyk/src/kevm_pyk/kdist/api.py
  kevm-pyk/src/kevm_pyk/kompile.py
  kevm-pyk/src/tests/integration/test_conformance.py
  kevm-pyk/src/tests/integration/test_kast.py
  kevm-pyk/src/tests/integration/test_run.py
  package/version
Labels: automerge

#2194 Ensure #checkCall branch exploration
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  package/version
Labels: bug

#2197 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/tests/integration/test_prove.py
  package/version
  tests/specs/benchmarks/README.md
  tests/specs/bihu/functional-spec.k
  tests/specs/erc20/functional-spec.k
  tests/specs/examples/erc20-spec.md
  tests/specs/examples/erc721-spec.md
  tests/specs/examples/storage-spec.md
  tests/specs/functional/evm-int-simplifications-spec.k
  tests/specs/functional/infinite-gas-spec.k
  tests/specs/mcd/functional-spec.k
Labels: automerge
