Repository runtimeverification/evm-semantics, pull requests merged in 2024-08, with the labels that each got.

#2548 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2554 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2555 proxy: install-build-deps: Automate installation of required system packages
  README.md
  install-build-deps
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2562 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2563 Add `--maintenance-rate` option
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/cli.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: automerge

#2564 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2566 Partial evaluation of EVM optimization lemmas
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/optimizations.md
  kevm-pyk/src/tests/integration/test_prove.py
  package/version
Labels: automerge

#2567 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2569 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2568 Adding support for the `--assume-defined` flag
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/cli.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: enhancement, automerge

#2570 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2557 Enable Outside Collaborators to run test suite before PR's are reviewed / merged
  .github/workflows/master-push.yml
  .github/workflows/release.yml
  .github/workflows/test-pr.yml
  package/version.sh
Labels: automerge

#2572 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/cli.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: automerge

#2574 Hotfix/push release with pat
  .github/workflows/master-push.yml
Labels: automerge

#2577 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2578 Update dependency: deps/z3
  deps/z3
Labels: automerge

#2580 Change symbolic-constructor flag to symbolic-immutables
  kevm-pyk/src/kevm_pyk/cli.py
Labels: automerge

#2581 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2582 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2387 Build semantics using `krypto.a`
  .github/workflows/Dockerfile
  .github/workflows/update-version.yml
  README.md
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/src/kevm_pyk/kdist/plugin.py
  kevm-pyk/src/kevm_pyk/kompile.py
Labels: automerge

#2556 proxy: Update link from unofficial nixos wiki to official one
  README.md
Labels: automerge

#2584 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2585 Add option string for symbolic-immutables
  kevm-pyk/src/kevm_pyk/cli.py
Labels: bug

#2583 Stronger bounds on symbolic block.timestamp and block.number
  kevm-pyk/src/kevm_pyk/kevm.py
Labels: enhancement, automerge

#2589 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2591 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2592 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2593 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2594 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2597 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2601 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge
