Repository runtimeverification/evm-semantics, pull requests merged in 2024-06, with the labels that each got.

#2441 Compute jumpdests using the KCFGSemantics.custom_step heuristic
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  kevm-pyk/src/tests/unit/test_kevm.py
  package/version
  tests/specs/kontrol/test-allowchangestest-testallow-0-spec.k
  tests/specs/kontrol/test-allowchangestest-testallow_fail-0-spec.k
  tests/specs/kontrol/test-allowchangestest-testfailallowcallstoaddress-0-spec.k
  tests/specs/kontrol/test-allowchangestest-testfailallowchangestostorage-0-spec.k
  tests/specs/kontrol/test-countertest-testincrement-0-spec.k
  tests/specs/kontrol/test-expectreverttest-test_expectrevert_bytes4-0-spec.k
  tests/specs/kontrol/test-expectreverttest-test_expectrevert_message-0-spec.k
  tests/specs/kontrol/test-expectreverttest-test_expectrevert_returnvalue-0-spec.k
  tests/specs/kontrol/test-expectreverttest-testfail_expectrevert_bytes4-0-spec.k
  tests/specs/kontrol/test-expectreverttest-testfail_expectrevert_failandsuccess-0-spec.k
  tests/specs/kontrol/test-expectreverttest-testfail_expectrevert_false-0-spec.k
  tests/specs/kontrol/test-owneruponlytest-testincrementasowner-0-spec.k
  tests/specs/kontrol/test-safetest-testwithdrawfuzz-uint96-0-spec.k
Labels: automerge

#2458 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2459 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2453 remove default values from argparse
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/cli.py
  package/version
Labels: bug, automerge

#2455 Change formula for #sizeOfDynamicType(#array)
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/abi.md
  package/version
  tests/specs/functional/abi-spec.k
Labels: bug, automerge

#2460 Avoid PUSH data when computing jumpdests
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  kevm-pyk/src/tests/unit/test_kevm.py
  package/version
  tests/specs/kontrol/test-allowchangestest-testallow-0-spec.k
  tests/specs/kontrol/test-allowchangestest-testallow_fail-0-spec.k
  tests/specs/kontrol/test-allowchangestest-testfailallowcallstoaddress-0-spec.k
  tests/specs/kontrol/test-allowchangestest-testfailallowchangestostorage-0-spec.k
  tests/specs/kontrol/test-countertest-testincrement-0-spec.k
  tests/specs/kontrol/test-expectreverttest-test_expectrevert_bytes4-0-spec.k
  tests/specs/kontrol/test-expectreverttest-test_expectrevert_message-0-spec.k
  tests/specs/kontrol/test-expectreverttest-test_expectrevert_returnvalue-0-spec.k
  tests/specs/kontrol/test-expectreverttest-testfail_expectrevert_bytes4-0-spec.k
  tests/specs/kontrol/test-expectreverttest-testfail_expectrevert_failandsuccess-0-spec.k
  tests/specs/kontrol/test-expectreverttest-testfail_expectrevert_false-0-spec.k
  tests/specs/kontrol/test-owneruponlytest-testincrementasowner-0-spec.k
  tests/specs/kontrol/test-safetest-testwithdrawfuzz-uint96-0-spec.k
Labels: bug, automerge

#2463 Eliminate complex KLabels from Python code
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/abi.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/buf.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm-types.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/hashed-locations.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/serialization.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/word.md
  package/version
Labels: enhancement

#2461 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2465 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2464 Replace `klabel(_)` and `symbol` attrs with `symbol(_)`
  README.md
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/edsl.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/gas.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/hashed-locations.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/json-rpc.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/schedule.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/serialization.md
  package/version
Labels: automerge

#2468 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: automerge

#2470 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2466 Add option to use `booster-dev` binary for execution of proofs
  .github/workflows/test-pr.yml
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/cli.py
  kevm-pyk/src/tests/conftest.py
  kevm-pyk/src/tests/integration/test_prove.py
  package/version
  tests/failing-symbolic.haskell-booster-dev
Labels: automerge

#2473 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2471 Have <jumpDests> as Bytes instead of Set
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/cli.py
  kevm-pyk/src/kevm_pyk/kevm.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/state-utils.md
  kevm-pyk/src/tests/unit/test_kevm.py
  package/version
  tests/failing/ContractCreationSpam_d0g0v0.json.expected
  tests/failing/static_callcodecallcodecall_110_OOGMAfter_2_d0g0v0.json.expected
  tests/specs/examples/sum-to-n-foundry-spec.k
  tests/specs/kontrol/test-allowchangestest-testallow-0-spec.k
  tests/specs/kontrol/test-allowchangestest-testallow_fail-0-spec.k
  tests/specs/kontrol/test-allowchangestest-testfailallowcallstoaddress-0-spec.k
  tests/specs/kontrol/test-allowchangestest-testfailallowchangestostorage-0-spec.k
  tests/specs/kontrol/test-arithmetictest-test_max1_broken-uint256-uint256-0-spec.k
  tests/specs/kontrol/test-arithmetictest-test_wdiv_rounding-uint256-uint256-0-spec.k
  tests/specs/kontrol/test-arithmetictest-test_wmul_wdiv_inverse_underflow-uint256-uint256-0-spec.k
  tests/specs/kontrol/test-arithmetictest-test_wmul_weakly_increasing_positive-uint256-uint256-0-spec.k
  tests/specs/kontrol/test-countertest-testincrement-0-spec.k
  tests/specs/kontrol/test-emitcontracttest-testexpectemit-0-spec.k
  tests/specs/kontrol/test-emitcontracttest-testexpectemitcheckemitter-0-spec.k
  tests/specs/kontrol/test-emitcontracttest-testexpectemitdonotcheckdata-0-spec.k
  tests/specs/kontrol/test-expectcalltest-testexpectregularcall-0-spec.k
  tests/specs/kontrol/test-expectcalltest-testexpectstaticcall-0-spec.k
  tests/specs/kontrol/test-expectreverttest-test_expectrevert_bytes4-0-spec.k
  tests/specs/kontrol/test-expectreverttest-test_expectrevert_message-0-spec.k
  tests/specs/kontrol/test-expectreverttest-test_expectrevert_returnvalue-0-spec.k
  tests/specs/kontrol/test-expectreverttest-testfail_expectrevert_bytes4-0-spec.k
  tests/specs/kontrol/test-expectreverttest-testfail_expectrevert_failandsuccess-0-spec.k
  tests/specs/kontrol/test-expectreverttest-testfail_expectrevert_false-0-spec.k
  tests/specs/kontrol/test-owneruponlytest-testincrementasowner-0-spec.k
  tests/specs/kontrol/test-safetest-testwithdrawfuzz-uint96-0-spec.k
  tests/specs/kontrol/test-storetest-testaccesses-0-spec.k
  tests/specs/kontrol/test-storetest-teststoreload-0-spec.k
Labels: enhancement, automerge

#2474 Refactor opcode optimization proofs, delete useless proofs
  .github/workflows/test-pr.yml
  Makefile
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/optimizations.md
  kevm-pyk/src/kevm_pyk/utils.py
  kevm-pyk/src/tests/integration/test_prove.py
  package/version
  tests/failing-symbolic.haskell
  tests/failing-symbolic.haskell-booster
  tests/failing-symbolic.haskell-booster-dev
  tests/failing-symbolic.pyk
  tests/specs/bihu/collectToken-spec.k
  tests/specs/bihu/forwardToHotWallet-failure-1-spec.k
  tests/specs/bihu/forwardToHotWallet-failure-2-spec.k
  tests/specs/bihu/forwardToHotWallet-failure-3-spec.k
  tests/specs/bihu/forwardToHotWallet-failure-4-spec.k
  tests/specs/bihu/forwardToHotWallet-success-1-spec.k
  tests/specs/bihu/forwardToHotWallet-success-2-spec.k
  tests/specs/bihu/functional-spec.k
  tests/specs/bihu/verification.k
  tests/specs/opcodes/create-spec.k
  tests/specs/opcodes/verification.k
  tests/specs/smoke
Labels: automerge

#2477 Pass remaining benchmarks, lemmas, and delete unused proofs
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
  tests/failing-symbolic.haskell
  tests/failing-symbolic.haskell-booster
  tests/failing-symbolic.haskell-booster-dev
  tests/failing-symbolic.pyk
  tests/specs/benchmarks/functional-spec.k
  tests/specs/benchmarks/verification.k
  tests/specs/functional/lemmas-no-smt-spec.k
  tests/specs/functional/lemmas-spec.k
  tests/specs/kontrol/test-arithmetictest-test_wmul_wdiv_inverse_underflow-uint256-uint256-0-spec.k
  tests/specs/mcd/dstoken-burn-self-fail-rough-spec.k
  tests/specs/mcd/dstoken-transferfrom-fail-rough-spec.k
  tests/specs/mcd/flapper-tend-guy-diff-pass-rough-spec.k
  tests/specs/mcd/gemjoin-exit-pass-rough-spec.k
  tests/specs/mcd/vow-cage-deficit-pass-rough-spec.k
  tests/specs/mcd/vow-cage-surplus-pass-rough-spec.k
Labels: automerge

#2478 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2482 Improve performance of large lemmas proof suite
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/tests/integration/test_prove.py
  package/version
Labels: automerge

#2481 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2467 Factor out vat arithmetic in proof-reuse for MCD
  .github/workflows/test-pr.yml
  Makefile
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/cli.py
  kevm-pyk/src/kevm_pyk/utils.py
  kevm-pyk/src/tests/integration/test_prove.py
  package/version
  tests/failing-symbolic.haskell
  tests/failing-symbolic.haskell-booster
  tests/failing-symbolic.haskell-booster-dev
  tests/failing-symbolic.pyk
  tests/specs/mcd/flopper-cage-pass-spec.k
  tests/specs/mcd/vat-arithmetic-spec.k
  tests/specs/mcd/vat-dai-pass-spec.k
  tests/specs/mcd/vat-flux-diff-pass-rough-spec.k
  tests/specs/mcd/vat-flux-diff-pass-spec.k
  tests/specs/mcd/vat-fold-pass-rough-spec.k
  tests/specs/mcd/vat-fork-diff-pass-rough-spec.k
  tests/specs/mcd/vat-frob-diff-zero-dart-pass-rough-spec.k
  tests/specs/mcd/vat-heal-pass-spec.k
  tests/specs/mcd/vat-move-diff-rough-spec.k
  tests/specs/mcd/vat-mului-pass-spec.k
  tests/specs/mcd/vat-sin-pass-spec.k
  tests/specs/mcd/vat-slip-pass-rough-spec.k
  tests/specs/mcd/vat-spec.k
Labels: enhancement, automerge

#2484 Run and pass remaining two functional proof suites on Booster
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/serialization.md
  package/version
  tests/failing-symbolic.haskell-booster
  tests/specs/functional/merkle-spec.k
  tests/specs/functional/storageRoot-spec.k
Labels: automerge

#2483 Update dependency: deps/k_release
  .github/workflows/update-version.yml
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
  tests/failing-symbolic.haskell-booster-dev
Labels: automerge

#2486 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2488 Refactor sender function
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/driver.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm-types.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/serialization.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/state-utils.md
  package/version
Labels: bug, automerge

#2492 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2496 Update dependency: deps/k_release
  .github/workflows/update-version.yml
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2498 Update dependency: deps/k_release
  .github/workflows/update-version.yml
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2480 Pass remaining proofs with RPC prover
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/tests/integration/test_prove.py
  package/version
  tests/failing-symbolic.haskell
  tests/failing-symbolic.haskell-booster
  tests/specs/examples/erc721-spec.md
  tests/specs/examples/sum-to-n-foundry-spec.k
  tests/specs/examples/sum-to-n-spec.k
Labels: automerge

#2485 Remove `kprove` legacy style prover
  .github/workflows/test-pr.yml
  Makefile
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/cli.py
  kevm-pyk/src/kevm_pyk/kevm.py
  kevm-pyk/src/tests/integration/test_prove.py
  package/version
  tests/failing-symbolic.haskell
  tests/specs/examples/README.md
Labels: automerge

#2499 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2500 Remove testing pure `kore-rpc` on CI
  .github/workflows/test-pr.yml
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/cli.py
  kevm-pyk/src/tests/integration/test_prove.py
  package/version
  tests/failing-symbolic.pyk
Labels: automerge

#2501 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2502 Improve harness for conformance tests
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/tests/integration/test_conformance.py
  package/version
  tests/slow.llvm
Labels: enhancement, automerge

#2503 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2505 Tweaks to the conformance harness
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/tests/integration/test_conformance.py
  package/version
  tests/slow.llvm
Labels: enhancement, automerge

#2497 Reflect `ignore_warnings` kompile option
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kompile.py
  package/version
Labels: enhancement, automerge

#2504 Separate functional specifications into own CI job
  .github/workflows/test-pr.yml
  Makefile
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/tests/integration/test_prove.py
  package/version
Labels: automerge
