Repository runtimeverification/evm-semantics, pull requests merged in 2024-07, with the labels that each got.

#2508 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: automerge

#2378 Deprecate `symbol` and `klabel(_)`
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/asm.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/buf.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/driver.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm-types.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/gas.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/json-rpc.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/network.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/serialization.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/state-utils.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/word.md
  package/version
  tests/interactive/sumTo10.evm.parse-expected
Labels: automerge

#2513 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2516 Enabling functional proofs in Kontrol
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  package/version
Labels: bug, automerge

#2514 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2515 Add link to Kontrol tg channel to failure output
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: automerge

#2517 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2519 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2518 Add option to use sequential proof loop
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/cli.py
  kevm-pyk/src/kevm_pyk/utils.py
  kevm-pyk/src/tests/conftest.py
  kevm-pyk/src/tests/integration/test_prove.py
  package/version
Labels: enhancement, automerge

#2522 Add transient_storage parameter to KEVM.account_cell
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  package/version
Labels: automerge

#2523 Fix indexed reference to nonce cell
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  package/version
Labels: automerge

#2521 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2524 Replace `run_process` by `run_process_2`
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/interpreter.py
  kevm-pyk/src/kevm_pyk/kdist/plugin.py
  kevm-pyk/src/kevm_pyk/kompile.py
  package/version
Labels: automerge

#2525 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2526 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2528 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2529 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2530 Test for previously added simplification
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
  tests/specs/functional/lemmas-spec.k
Labels: automerge, engagement

#2533 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2535 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2534 eip-5656: implement MCOPY opcode
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/asm.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/schedule.md
  package/version
  tests/failing.llvm
Labels: enhancement

#2536 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2538 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2539 Update dependency: deps/k_release
  .github/workflows/test-pr.yml
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
  tests/specs/functional/lemmas-no-smt-spec.k
Labels: automerge

#2542 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2544 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2543 Add status bar support
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: automerge

#2541 Execute multiple blocks in conformance tests
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/driver.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/state-utils.md
  package/version
  tests/failing/ContractCreationSpam_d0g0v0.json.expected
  tests/failing/static_callcodecallcodecall_110_OOGMAfter_2_d0g0v0.json.expected
Labels: automerge

#2532 Load claims using `ClaimLoader`
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: automerge
