Repository runtimeverification/evm-semantics, pull requests merged in 2024-02, with the labels that each got.

#2277 Add range constraints for TIMESTAMP_CELL
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  package/version
Labels: automerge

#2280 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2281 Give pytest an upper bound <8.0.0
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2282 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2283 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2279 Remove usages of `kore` attribute
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/evm-int-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/int-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/lemmas.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/optimizations.md
  optimizer/optimizations.md
  package/version
  tests/specs/benchmarks/verification.k
  tests/specs/bihu/verification.k
  tests/specs/mcd/verification.k
  tests/specs/mcd/word-pack.k
Labels: automerge

#2284 Suppress cpp warnings by default when kompiling the llvm-backend
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kompile.py
  package/version
Labels: enhancement

#2285 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2262 Add targets for KLLVM bindings
  .github/workflows/test-pr.yml
  README.md
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kdist/plugin.py
  kevm-pyk/src/kevm_pyk/kompile.py
  package/version
Labels: automerge

#2286 Additional arithmetic reasoning needed for symbolic bytes
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/bitwise-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/bytes-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/evm-int-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/int-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/lemmas.k
  package/version
  tests/specs/functional/lemmas-spec.k
Labels: automerge

#2243 Enable options for controlling booster execution
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/cli.py
  kevm-pyk/src/kevm_pyk/utils.py
  kevm-pyk/src/tests/conftest.py
  kevm-pyk/src/tests/integration/test_prove.py
  package/version
Labels: enhancement, automerge

#2270 Adding further lemmas for bitwise reasoning
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/bitwise-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/bytes-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/evm-int-simplification.k
  package/version
  tests/specs/benchmarks/verification.k
  tests/specs/functional/lemmas-spec.k
  tests/specs/mcd/verification.k
Labels: enhancement

#2287 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  package/version
Labels: automerge

#2293 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2244 Upstream specifications from Kontrol test-suite
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/evm-int-simplification.k
  kevm-pyk/src/tests/integration/test_prove.py
  package/version
  tests/failing-symbolic.haskell
  tests/failing-symbolic.pyk
  tests/specs/kontrol/test-allowchangestest-testallow-0-spec.k
  tests/specs/kontrol/test-allowchangestest-testallow_fail-0-spec.k
  tests/specs/kontrol/test-allowchangestest-testfailallowcallstoaddress-0-spec.k
  tests/specs/kontrol/test-allowchangestest-testfailallowchangestostorage-0-spec.k
  tests/specs/kontrol/test-arithmetictest-test_max1_broken-uint256-uint256-0-spec.k
  tests/specs/kontrol/test-arithmetictest-test_wdiv_rounding-uint256-uint256-0-spec.k
  tests/specs/kontrol/test-arithmetictest-test_wmul_wdiv_inverse_underflow-uint256-uint256-0-spec.k
  tests/specs/kontrol/test-arithmetictest-test_wmul_weakly_increasing_positive-uint256-uint256-0-spec.k
  tests/specs/kontrol/test-countertest-testincrement-0-spec.k
  tests/specs/kontrol/test-emitcontracttest-testexpectemit-0-spec.k
  tests/specs/kontrol/test-emitcontracttest-testexpectemitcheckemitter-0-spec.k
  tests/specs/kontrol/test-emitcontracttest-testexpectemitdonotcheckdata-0-spec.k
  tests/specs/kontrol/test-expectcalltest-testexpectregularcall-0-spec.k
  tests/specs/kontrol/test-expectcalltest-testexpectstaticcall-0-spec.k
  tests/specs/kontrol/test-expectreverttest-test_expectrevert_bytes4-0-spec.k
  tests/specs/kontrol/test-expectreverttest-test_expectrevert_message-0-spec.k
  tests/specs/kontrol/test-expectreverttest-test_expectrevert_returnvalue-0-spec.k
  tests/specs/kontrol/test-expectreverttest-testfail_expectrevert_bytes4-0-spec.k
  tests/specs/kontrol/test-expectreverttest-testfail_expectrevert_failandsuccess-0-spec.k
  tests/specs/kontrol/test-expectreverttest-testfail_expectrevert_false-0-spec.k
  tests/specs/kontrol/test-owneruponlytest-testincrementasowner-0-spec.k
  tests/specs/kontrol/test-safetest-testwithdrawfuzz-uint96-0-spec.k
  tests/specs/kontrol/test-storetest-testaccesses-0-spec.k
  tests/specs/kontrol/test-storetest-teststoreload-0-spec.k
  tests/specs/kontrol/verification.k
Labels: enhancement, automerge

#2296 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2297 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2298 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: automerge

#2299 Small cleanups/simplifications to run_prover
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: automerge

#2300 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: automerge

#2303 Change default `fast-check-subsumption` to `false`
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/cli.py
  package/version
Labels: automerge

#2301 Streamlining #asWord simplifications
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/bytes-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/evm-int-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/lemmas.k
  package/version
  tests/specs/functional/lemmas-spec.k
Labels: enhancement, automerge

#2309 Drop . in favour of .K
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/driver.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/optimizations.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/state-utils.md
  package/version
Labels: automerge

#2307 Lemmas and tests needed for symbolic bytes manipulation
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/bitwise-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/bytes-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/evm-int-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/int-simplification.k
  package/version
  tests/specs/functional/lemmas-spec.k
Labels: enhancement

#2306 fix bug in computation of miner balance after tx if miner == sender
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  package/version
  tests/failing.llvm
Labels: automerge

#2311 Additional constraints for simplifications of PR #2307
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/bytes-simplification.k
  package/version
Labels: automerge

#2310 only check nonce on CREATE and CREATE2
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  package/version
  tests/failing.llvm
Labels: automerge

#2312 Add attribute `klabel` to unquoted productions
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/abi.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/asm.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/buf.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/driver.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm-types.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/gas.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/hashed-locations.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/json-rpc.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/network.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/serialization.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/state-utils.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/word.md
  package/version
Labels: automerge

#2260 Annotating rules that preserve definedness
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  package/version
  tests/failing-symbolic.haskell-booster
Labels: automerge

#2302 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/utils.py
  kevm-pyk/src/tests/integration/test_kast.py
  kevm-pyk/src/tests/integration/test_run.py
  package/version
  tests/failing/ContractCreationSpam_d0g0v0.json.expected
  tests/failing/static_callcodecallcodecall_110_OOGMAfter_2_d0g0v0.json.expected
  tests/interactive/CallRecursiveContract_d0g0v0.json.parse-expected
  tests/interactive/log3_MaxTopic_d0g0v0.json.parse-expected
  tests/interactive/sumTo10.evm.parse-expected
  tests/interactive/vmLogTest/log3.gst-to-kore.expected
Labels: automerge

#2316 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: automerge

#2317 Strengthening KEVM invariant
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  package/version
Labels: enhancement

#2315 Moving `#accessStorage` logic back to gas calculations
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  package/version
Labels: enhancement, automerge

#2304 Adds the exception to proof.error_info
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: automerge

#2320 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge
