Repository runtimeverification/evm-semantics, pull requests merged in 2024-09, with the labels that each got.

#2599 Update doc
  .gitignore
  Makefile
  README.md
Labels: automerge

#2603 Update dependency: deps/k_release
  .github/workflows/update-version.yml
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2608 Forcing sequential proof advancement in CI
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/tests/integration/test_prove.py
Labels: enhancement, automerge

#2609 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  tests/specs/examples/sum-to-n-foundry-spec.k
Labels: automerge

#2605 Stabilising bool2Word reasoning
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm-types.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/lemmas.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/word.md
  tests/specs/functional/lemmas-spec.k
  tests/specs/mcd-structured/verification.k
  tests/specs/mcd/verification.k
Labels: enhancement, automerge

#2606 Cleanup of slot-update-related content
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/bitwise-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/slot-updates.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/word.md
  tests/specs/benchmarks/functional-spec.k
  tests/specs/functional/lemmas-spec.k
  tests/specs/mcd-structured/flopper-file-pass-rough-spec.k
  tests/specs/mcd-structured/verification.k
  tests/specs/mcd/flopper-file-pass-rough-spec.k
Labels: enhancement, automerge

#2610 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2611 Typos and minor lemma clean-up
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm-types.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/serialization.md
Labels: automerge

#2612 Removing some unneeded lemmas
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/bitwise-simplification.k
  tests/specs/functional/lemmas-spec.k
Labels: enhancement

#2614 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2613 Stabilising `chop` lemmas
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/evm-int-simplification.k
  tests/specs/functional/lemmas-spec.k
Labels: enhancement, automerge

#2618 Correcting the `sum-to-n-foundry-spec.k` circularity test
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/lemmas.k
  tests/specs/examples/sum-to-n-foundry-spec.k
Labels: enhancement, automerge

#2619 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2604 #asWord simplifications
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/bitwise-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/bytes-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/evm-int-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/lemmas.k
  tests/specs/benchmarks/verification.k
  tests/specs/examples/storage-spec.md
  tests/specs/functional/lemmas-spec.k
Labels: enhancement, automerge

#2621 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2622 Upstreaming Kontrol slot update lemmas as tests
  tests/specs/functional/slot-updates-spec.k
Labels: enhancement

#2623 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge

#2625 Correction for `#asWord` lemmas
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/evm-int-simplification.k
Labels: bug

#2630 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/kevm.py
Labels: automerge

#2631 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
Labels: automerge
