Repository runtimeverification/evm-semantics, pull requests merged in 2024-01, with the labels that each got.

#2242 Semantics specific options for controlling execution
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/cli.py
  kevm-pyk/src/kevm_pyk/kevm.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  package/version
Labels: automerge

#2246 Add option for breaking on basic blocks
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/cli.py
  kevm-pyk/src/kevm_pyk/kevm.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  package/version
Labels: automerge

#2239 Moving `#accessAccounts` and `#accessStorage` logic out of gas-related calculations
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  package/version
Labels: enhancement, automerge

#2236 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  package/version
Labels: automerge

#2249 Add accounts invariants
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  package/version
Labels: automerge

#2253 Avoid generating cell-fragments during execution
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  package/version
Labels: automerge

#2251 Generalising bitwise simplifications
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/bitwise-simplification.k
  package/version
  tests/specs/functional/lemmas-spec.k
Labels: enhancement, automerge

#2254 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2247 mark some key simplifications as preserves-definedness (for booster usage)
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/buf.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/bitwise-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/bytes-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/evm-int-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/int-simplification.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/lemmas/lemmas.k
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/serialization.md
  package/version
  tests/specs/bihu/verification.k
Labels: automerge

#2258 Make `fail-fast`, `no-break-on-calls`, `counterexample-information` default
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/cli.py
  package/version
Labels: automerge

#2261 make #gasExec(EXP _ _) preserve definedness
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  package/version
Labels: automerge

#2256 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2263 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2264 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2229 De-duplication of use-gas-related rules
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/optimizations.md
  package/version
Labels: enhancement, automerge

#2266 Insert Dependabot updates
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
  web/package-lock.json
Labels: automerge

#2267 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2268 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2259 Rule list display, breaking on stepping into calls
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  kevm-pyk/src/kevm_pyk/kevm.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/evm.md
  package/version
Labels: automerge

#2269 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/utils.py
  package/version
Labels: automerge

#2276 Mark claims as trusted, skip when they are
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/__main__.py
  package/version
  tests/specs/mcd/vat-move-diff-rough-spec.k
  tests/specs/mcd/vat-slip-pass-rough-spec.k
Labels: automerge

#2273 Refactor #tuple encoding to support dynamic structs
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/abi.md
  kevm-pyk/src/kevm_pyk/kproj/evm-semantics/buf.md
  package/test-package.sh
  package/version
  tests/specs/benchmarks/structarg01-spec.k
  tests/specs/benchmarks/structarg01.sol
  tests/specs/smoke
Labels: enhancement, automerge, engagement

#2272 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge

#2278 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kevm-pyk/poetry.lock
  kevm-pyk/pyproject.toml
  kevm-pyk/src/kevm_pyk/__init__.py
  package/version
Labels: automerge
